addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      # We need a system-wide libicu
      - libicu-dev
      # Package list from http://bazel.io/docs/install.html
      - openjdk-7-jdk
      - openjdk-7-source
      - pkg-config
      - zip
      # - g++  # provided by g++-4.9
      - zlib1g-dev

# Eventually, Bazel will have binary packages and we'll be able to
# just download a prebuilt distribution of Bazel. For now, build it
# from source every time.
before_install:
  - git clone https://github.com/google/bazel.git 
  - pushd bazel
  - git checkout d93990f9ae43146dba1e6b57730907b69685a75f
  - cp -r ../tools/bazel-travis/custom_crosstool ./custom_crosstool
  - BAZELRC=../tools/bazel-travis/bazelrc ./compile.sh
  - popd

script:
  - bazel/output/bazel test //prometheus/...
